StudentsCircle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminn/', include('adminn.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('student.urls')),
    path('union/', include('union.urls')),
    # path('chat/', include('chat.urls')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# userprofile  = timeline.html/pitpoint-detail.html/pittube-channel.html/
# youtube brain wash for code: - mr robots, cilicon vally

chat/urls.py
from django.urls import path
from .views import index, room
app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

student/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UserHomeView, add_comment, add_like, Timeline, \
    ProfileView, Friends, Unions, edit_fullname, edit_profile_data, \
    select_my_union, upload_pp, chat_room, upload_bg, SingleUserDetailView, SinglePostDetailView, SinglePostUpdateView, \
    SinglePostDeleteView

app_name = 'student'


urlpatterns = [
    path('', UserHomeView.as_view(), name='home'),

    path('add_cmnt/', add_comment, name='add_cmnt'),
    path('add_like/', add_like, name='add_like'),
    path('edit_fullname/', edit_fullname, name='edit_fullname'),
    path('edit_profile_data/', edit_profile_data, name='edit_profile_data'),
    path('select_my_union/', select_my_union, name='select_my_union'),
    path('upload_pp/', upload_pp, name='upload_pp'),
    path('upload_bg/', upload_bg, name='upload_bg'),
    path('chat_room/<int:pk>', chat_room, name='chat_room'),

    path('posts/<int:pk>', UserHomeView.as_view(), name='detail'),
    path('details/<int:pk>', SingleUserDetailView.as_view(), name='details'),
    path('post_details/<int:pk>', SinglePostDetailView.as_view(), name='post_details'),
    path('post_update/<int:pk>', SinglePostUpdateView.as_view(), name='post_update'),
    path('post_delete/<int:pk>', SinglePostDeleteView.as_view(), name='post_delete'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('timeline/', Timeline.as_view(), name='timeline'),
    path('friends/', Friends.as_view(), name='friends'),
    path('unions/', Unions.as_view(), name='unions'),



]

union/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UnionDetailView, MyUnionDetailView, UnionAdminView, union_join_req, upload_union_pp, \
    upload_union_bg, edit_profile_data

app_name = 'union'

urlpatterns = [
    path('details/<int:pk>', UnionDetailView.as_view(), name='details'),
    path('my_union', MyUnionDetailView.as_view(), name='my_union'),
    path('union_admin', UnionAdminView.as_view(), name='union_admin'),
    path('join_req/', union_join_req, name='union_join_req'),
    path('upload_union_pp/', upload_union_pp, name='upload_union_pp'),
    path('upload_union_bg/', upload_union_bg, name='upload_union_bg'),
    path('edit_profile_data/', edit_profile_data, name='edit_profile_data'),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_save


# Create your models here.


class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True, unique=True)
    email = models.EmailField(max_length=150, blank=True, null=True, unique=True)
    is_verified = models.BooleanField(default=False)
    is_union = models.BooleanField(default=False)
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return str(self.username)

    def get_absolute_url(self):
        return reverse('student:details', args=[self.pk])


class Union(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    reg_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    est_date = models.DateField(null=True, blank=True)
    background_img = models.ImageField(upload_to='bg_pic/', height_field=None, width_field=None, null=True)
    logo = models.ImageField(upload_to='union_logo/', height_field=None, width_field=None, null=True)
    college_name = models.CharField(max_length=150, blank=True, null=True)
    college_short_name = models.CharField(max_length=30, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    college_est_date = models.DateField(null=True, blank=True)
    college_logo = models.ImageField(upload_to='collage_logo/', height_field=None, width_field=None, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created

    def __str__(self):
        return str(self.user)


GENDER = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default='Male', null=True, blank=True)
    admission_num = models.BigIntegerField(blank=True, null=True, unique=True)
    batch = models.CharField(max_length=200, blank=True, null=True)
    batch_num = models.BigIntegerField(blank=True, null=True, unique=True)
    union = models.ForeignKey(Union, on_delete=models.CASCADE, blank=True, null=True)
    membership_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    membership_img = models.ImageField(upload_to='memb_pic/', height_field=None, width_field=None, blank=True,
                                       null=True)
    profile_img = models.ImageField(upload_to='profile_pic/', height_field=None, width_field=None, blank=True,
                                    null=True)
    background_img = models.ImageField(upload_to='background_pic/', height_field=None, width_field=None, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created
    # general info
    hobbies = models.TextField(blank=True, null=True)
    interests = ArrayField(models.CharField(max_length=10, default='Arabic', blank=True, null=True), null=True)


def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Student.objects.create(user=instance)
        except:
            pass
# post_save.connect(post_save_user_model_receiver, sender=User)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_user')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


# Explorer, Talker, Admirer, Searcher, Groups and Events


class PointBadges(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userbadge')
    point = models.BigIntegerField(blank=True, null=True)
    badge = ArrayField(models.CharField(max_length=10, default="starter", blank=True, null=True), null=True)


class MemberRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_member')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_member')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


class PageAdmin(models.Model):
    page = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='page')
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

chat/models.py
from django.db import models

# Create your models here.

student/models.py
import uuid

from accounts.models import User
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.urls import reverse
from django.utils.text import slugify

# from .signals import delete_post_image , resize_post_image
from .utils import number, incrementor
from django.utils import timezone
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer


# Create your models here.


def upload_post_to(instance, filename):
    return f'post_image/{instance.user.username}/{filename}'


class PostManager(models.Manager):
    def get_posts(self, status: bool = False):
        return (
            self.get_queryset()
                .select_related("user", "user__profile")
                .prefetch_related("likes__profile", "comment_set__user__profile")
                .filter(archived=status)
        )


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=250, unique=False, null=True)
    image = models.FileField(null=True, blank=True, upload_to='post_images/', )
    filetype = models.CharField(max_length=10, blank=True, null=True)
    # likes = models.ManyToManyField(User, related_name="likes", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} : {self.text[:10]}"

    @property
    def image_url(self):
        if self.image == '':
            image = ''
        else:
            image = self.image.url
        return image

    def save(self, *args, **kwargs):
        self.slug = slugify(self.text[:5] + str(number()))
        if not self.image:
            self.image = ""
        if not self.text:
            self.text = ""
        return super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-created"]

    # to find url for each post
    def get_absolute_url(self):
        return reverse('student:detail', args=[self.slug])


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} : {self.user}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()


class SubComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    sub_com = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


# post_delete.connect(delete_post_image, sender=Post)
# post_save.connect(resize_post_image, sender=Post)


class Room(models.Model):
    room_name = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True, editable=False)
    user1 = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user2')


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='m_from_user')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='m_to_user')
    message_type = models.CharField(max_length=10, default='text')
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    message = models.TextField('message')
    # msg_img = models.ImageField(upload_to='msg_img/', height_field=None, width_field=None, blank=True, null=True)
    vid_img = models.FileField(upload_to='vid_img/', blank=True, null=True)
    # aud_img = models.FileField(upload_to='aud_img/', blank=True, null=True)
    # pdf_img = models.FileField(upload_to='pdf_img/', blank=True, null=True)




# class MessageModel(models.Model):
#     """
#     This class represents a chat message. It has a owner (user), timestamp and
#     the message body.
#
#     """
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user',
#                       related_name='m_from_user', db_index=True)
#     recipient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='recipient',
#                            related_name='m_to_user', db_index=True)
#     timestamp = models.DateTimeField('timestamp', auto_now_add=True, editable=False,
#                               db_index=True)
#     body = models.TextField('body')
#
#     def __str__(self):
#         return str(self.id)
#
#     def characters(self):
#         """
#         Toy function to count body characters.
#         :return: body's char number
#         """
#         return len(self.body)
#
#     def notify_ws_clients(self):
#         """
#         Inform client there is a new message.
#         """
#         notification = {
#             'type': 'recieve_group_message',
#             'message': '{}'.format(self.id)
#         }
#
#         channel_layer = get_channel_layer()
#         print("user.id {}".format(self.user.id))
#         print("user.id {}".format(self.recipient.id))
#
#         async_to_sync(channel_layer.group_send)("{}".format(self.user.id), notification)
#         async_to_sync(channel_layer.group_send)("{}".format(self.recipient.id), notification)
#
#     def save(self, *args, **kwargs):
#         """
#         Trims white spaces, saves the message and notifies the recipient via WS
#         if the message is new.
#         """
#         new = self.id
#         self.body = self.body.strip()  # Trimming whitespaces from the body
#         super(MessageModel, self).save(*args, **kwargs)
#         if new is None:
#             self.notify_ws_clients()
#
#     # Meta
#     class Meta:
#         app_label = 'student'

union/models.py
from django.db import models

# Create your models here.

student/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post, Comment
from accounts.models import User, Student


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'image']

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        # self.fields["image"].required = False
        # self.fields["text"].required = False
        self.fields["image"].widget.attrs.update({"id": "image_field"})
        self.fields["text"].widget.attrs.update({"id": "description_field"})

    def clean(self):
        cleaned_data = super().clean()
        text = cleaned_data.get('text')
        image = cleaned_data.get("image")
        print(text, image, '//////////////////////')

        if text == '' and image is None:
            raise ValidationError("D")

#
# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ['comment', 'post']
#
#     def __init__(self, *args, **kwargs) -> None:
#         super().__init__(*args, **kwargs)
#         self.fields["comment"].required = False
#         self.fields["post"].required = False
#
#         self.fields["comment"].widget.attrs.update({"id": "comment_field"})
#         self.fields["post"].widget.attrs.update({"value": "{{ po }}"})


class ProfileUpdateForm1(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number']


class ProfileUpdateForm2(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['location', 'birth_date', 'admission_num', 'batch_num']


class ProfileBgForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['background_img']

chat/views.py
from django.shortcuts import render


# Create your views here.


def index(request):
    return render(request, 'chat/index.html', {})


def room(request, room_name):
    # context = ''
    # context['room_name'] = room_name
    return render(request, 'chat/catroom.html', {'room_name': room_name})

templates/student/friends.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}

<section>
		<div class="gap2 gray-bg">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="row merged20" id="page-contents">
                            {% include 'student/profile_head.html' %}
							<div class="col-lg-12">
								<div class="central-meta">
									<div class="title-block">
										<div class="row">
											<div class="col-lg-6">
												<div class="align-left">
													<h5>Friends<span>{{ user.friends.count }}</span></h5>
												</div>
											</div>
											<div class="col-lg-6">
												<div class="row merged20">
													src/srt frd
<!--													<div class="col-lg-7 col-lg-7 col-sm-7">-->
<!--														<form method="post">-->
<!--															<input type="text" placeholder="Search Friend">-->
<!--															<button type="submit"><i class="fa fa-search"></i></button>-->
<!--														</form>-->
<!--													</div>-->
													<div class="col-lg-4 col-md-4 col-sm-4">
<!--														<div class="select-options">-->
<!--															<select class="select" style="display: none;">-->
<!--																<option>Sort by</option>-->
<!--																<option>A to Z</option>-->
<!--																<option>See All</option>-->
<!--																<option>Newest</option>-->
<!--																<option>oldest</option>-->
<!--															</select><div class="chosen-container chosen-container-single" style="width: 64px;" title=""><a class="chosen-single"><span>Sort by</span><div><b></b></div></a><div class="chosen-drop"><div class="chosen-search"><input type="text" autocomplete="off"></div><ul class="chosen-results"></ul></div></div>-->
<!--														</div>-->
													</div>
													<div class="col-lg-1 col-md-1 col-sm-1">
														<div class="option-list">
															<i class="fa fa-ellipsis-v"></i>
															<ul>
																<li><a title="" href="#">Show Friends Public</a></li>
																<li><a title="" href="#">Show Friends Private</a></li>
																<li><a title="" href="#">Mute Notifications</a></li>
															</ul>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div><!-- title block -->
								<div class="central-meta padding30">
									<div class="row">
										{% for fri in friends %}
											<div class="col-lg-3 col-md-6 col-sm-6">
											<div class="friend-box">
												<figure>
													<img src="{% static 'user/images/resources/frnd-cover1.jpg' %}" alt="">
													<span>Followers: {{ fri.friends.count }}</span>
												</figure>
												<div class="frnd-meta">
													<img src="{% static 'user/images/resources/frnd-figure1.jpg' %}" alt="">
													<div class="frnd-name">
														<a href="{% url 'student:details' fri.pk %}" title="">{{ fri.username|title }}</a>
														<span>{{ fri.student.location }}</span>
													</div>
													<ul class="frnd-info">
														<li><span>Friends:</span> {{ fri.friends.count }}</li>
														<li><span>Post:</span> {{ fri.post_set.count }}</li>
														<li><span>Since:</span> {{ fri.student.timestamp|date:"M d, Y" }}</li>
													</ul>
													<a href="{% url 'student:chat_room' pk=fri.pk %}" class="btn btn-primary" title="">Message</a>
<!--													<div class="more-opotnz">-->
<!--														<i class="fa fa-ellipsis-h"></i>-->
<!--														<ul>-->
<!--															<li><a href="#" title="">Block</a></li>-->
<!--															<li><a href="#" title="">UnBlock</a></li>-->
<!--															<li><a href="#" title="">Mute Notifications</a></li>-->
<!--															<li><a href="#" title="">hide from friend list</a></li>-->
<!--														</ul>-->
<!--													</div>-->
												</div>
											</div>
										</div>
										{% endfor %}

									</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>



{% endblock %}

templates/student/post_form.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<section>
    <div class="gap2">
        <div class="container">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <div class="central-meta">
                        {% if post.user == request.user %}
                        <div class="create-post">
                            <div class="user-fig"><!--user name and pp-->
                                {% if post.user.student.profile_img %}
                                    <img src=" {{ post.user.student.profile_img.url }} ">
                                {% else %}
                                    <img src="{% static 'user/images/male.png' %}">
                                {% endif %}
                                <a href="#" title="">{{ post.user }}</a>
                            </div><!--user name and pp-->
                        </div>
                        <div class="about-video">
                            <h6>Post Content</h6>
                            <div class="description">
                            <form method="post">{% csrf_token %}
                                {{ form.as_p }}
                                <input type="submit" value="Update">
                            </form>

                            </div><!--post text-->
                        </div>
                        {% else %}
                        <h1>You have no access to this post</h1>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
	var like_count = "{{ post.like_set.count }}"
</script>

<script src="{% static 'user/js/my-js.js' %}"></script>

{% endblock %}

templates/student/single_post.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section>
    <div class="gap2">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="central-meta">
                        <div class="create-post">
                            <div class="user-fig"><!--user name and pp-->
                                {% if post.user.student.profile_img %}
                                    <img src=" {{ post.user.student.profile_img.url }} ">
                                {% else %}
                                    <img src="{% static 'user/images/male.png' %}">
                                {% endif %}
                                <a href="#" title="">{{ post.user }}</a>
                            </div><!--user name and pp-->
                        </div>
                        <div class="about-video">
                            <h6>Post Content</h6>
                            {% if post.image_url %}
                                <figure>
                                    {% if post.filetype == 'image' %}
                                    <img src="{{ post.image_url }}" alt="img" style="object-fit: cover; max-height:500px">
                                    {% elif post.filetype == 'video' %}
                                    <video width="500" height="400" controls>
                                        <source src="{{ post.image_url }}" type="video/mp4">
                                        <source src="{{ post.image_url }}" type="video/ogg">
                                        Your browser does not support the video tag.
                                    </video>
                                    {% else %}
                                    <embed src="{{ post.image_url }}" width="500px" height="400px" />
                                    {% endif %}
                                </figure><!--post file-->
                            {% endif %}
                            <div class="description">
                                {% if post.user == request.user %}
                                <a id="delete_my_post" href="{% url 'student:post_delete' post.pk %}" class="learnmore" data-ripple="">Delete</a>
                                <a id="edit_my_post" href="{% url 'student:post_update' post.pk %}" class="learnmoreb" data-ripple="">Edit</a>
                                {% endif %}
                                <p class="read-more-wrap">{{ post.text }}</p>
                            </div><!--post text-->
                        </div>
                        <h6 class="comet-title"><i class="fa fa-comments"></i> Comments</h6>
                        <div class="coment-area" style="display: block">
                            <ul class="we-comet">
                                {% for comment in post.comment_set.all %}
                                    <li>
                                        <div class="comet-avatar">
                                            {% if comment.user.student.profile_img %}
                                                <img src=" {{ comment.user.student.profile_img.url }} " style="width:30px; height:30px; ">
                                            {% else %}
                                                <img src="{% static 'user/images/male.png' %}" style="width:30px; height:30px; ">
                                            {% endif %}
                                        </div>
                                        <div class="we-comment">
                                            <h5><a href="" title="">{{ comment.user }}</a></h5>
                                            <p>{{ comment.comment }}</p>
                                            <div class="inline-itms">
                                                <span>{{ comment.time }}</span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                                <li class="post-comment">
                                    <div class="comet-avatar">
                                        {% if user.student.profile_img %}
                                            <img src=" {{ user.student.profile_img.url }} " style="width:30px; height:30px; ">
                                        {% else %}
                                            <img src="{% static 'user/images/male.png' %}" style="width:30px; height:30px; ">
                                        {% endif %}
                                    </div>
                                    <div class="post-comt-box">
                                        <form>
                                            <textarea id="cmnt-{{post.id}}" placeholder="Post your comment"></textarea>
                                            <a class="cmnt_button main-btn2 p-2 m-2 mb-2" type="submit" data-post_id="{{post.id}}">send</a>
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="central-meta">
                        <span class="create-post">More Posts</span>
                        <div class="more-tube-psts">
                            {% for po in other_posts %}
                            <div>
                                {% if po.image_url %}
                                <figure style="width:50px; height:50px">
                                    {% if po.filetype == 'image' %}
                                        <img src="{{ po.image_url }}" alt="img" style="">
                                    {% elif po.filetype == 'video' %}
                                        <video controls style="width:50px; height:50px">
                                            <source src="{{ po.image_url }}" type="video/mp4">
                                            <source src="{{ po.image_url }}" type="video/ogg">
                                            Your browser does not support the video tag.
                                        </video>
                                    {% else %}
                                        <embed src="{{ po.image_url }}" style="width:50px; height:50px" />
                                    {% endif %}
                                </figure>
                                {% endif %}
                                <div class="tube-pst-meta">
                                    <h5><a href="{% url 'student:post_details' po.pk %}" title="">{{ po.text|slice:":50" }}</a></h5>
                                    <div class="user-fig">
                                        {% if po.user.student.profile_img %}
                                            <img src=" {{ po.user.student.profile_img.url }} ">
                                        {% else %}
                                            <img src="{% static 'user/images/male.png' %}">
                                        {% endif %}
                                        {% if po.user.is_union%}
                                            <a href="{% url 'union:details' po.user.pk %}" title="">{{ po.user }}</a>
                                        {% else %}
                                            <a href="{% url 'student:details' po.user.pk %}" title="">{{ po.user }}</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <hr class="mb-5">
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
	var like_count = "{{ post.like_set.count }}"
</script>

<script src="{% static 'user/js/my-js.js' %}"></script>

{% endblock %}