StudentsCircle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminn/', include('adminn.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('student.urls')),
    path('union/', include('union.urls')),
    # path('chat/', include('chat.urls')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# userprofile  = timeline.html/pitpoint-detail.html/pittube-channel.html/
# youtube brain wash for code: - mr robots, cilicon vally

accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView
from accounts.views import StudentRegister, UserLoginView, send_friend_request, otp_login, enter_otp

app_name = 'accounts'

urlpatterns = [
    # path('', TemplateView.as_view(template_name="accounts/home.html"), name='accounts'),
    path('student_register/', StudentRegister.as_view(), name='student_register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('login/', include('allauth.urls')),

    path('add_friend/', send_friend_request, name='add_friend'),
    path('otp_login/', otp_login, name='otp_login'),
    path('enter_otp/', enter_otp, name='enter_otp'),

]

chat/urls.py
from django.urls import path
from .views import index, room
app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_save


# Create your models here.


class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True, unique=True)
    email = models.EmailField(max_length=150, blank=True, null=True, unique=True)
    is_verified = models.BooleanField(default=False)
    is_union = models.BooleanField(default=False)
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return str(self.username)

    def get_absolute_url(self):
        return reverse('student:details', args=[self.pk])


class Union(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    reg_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    est_date = models.DateField(null=True, blank=True)
    background_img = models.ImageField(upload_to='bg_pic/', height_field=None, width_field=None, null=True)
    logo = models.ImageField(upload_to='union_logo/', height_field=None, width_field=None, null=True)
    college_name = models.CharField(max_length=150, blank=True, null=True)
    college_short_name = models.CharField(max_length=30, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    college_est_date = models.DateField(null=True, blank=True)
    college_logo = models.ImageField(upload_to='collage_logo/', height_field=None, width_field=None, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created

    def __str__(self):
        return str(self.user)


GENDER = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default='Male', null=True, blank=True)
    admission_num = models.BigIntegerField(blank=True, null=True, unique=True)
    batch = models.CharField(max_length=200, blank=True, null=True)
    batch_num = models.BigIntegerField(blank=True, null=True, unique=True)
    union = models.ForeignKey(Union, on_delete=models.CASCADE, blank=True, null=True)
    membership_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    membership_img = models.ImageField(upload_to='memb_pic/', height_field=None, width_field=None, blank=True,
                                       null=True)
    profile_img = models.ImageField(upload_to='profile_pic/', height_field=None, width_field=None, blank=True,
                                    null=True)
    background_img = models.ImageField(upload_to='background_pic/', height_field=None, width_field=None, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created
    # general info
    hobbies = models.TextField(blank=True, null=True)
    interests = ArrayField(models.CharField(max_length=10, default='Arabic', blank=True, null=True), null=True)


def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Student.objects.create(user=instance)
        except:
            pass
# post_save.connect(post_save_user_model_receiver, sender=User)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_user')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


# Explorer, Talker, Admirer, Searcher, Groups and Events


class PointBadges(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userbadge')
    point = models.BigIntegerField(blank=True, null=True)
    badge = ArrayField(models.CharField(max_length=10, default="starter", blank=True, null=True), null=True)


class MemberRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_member')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_member')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


class PageAdmin(models.Model):
    page = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='page')
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import transaction
from .models import User, Student, Union


class StudentSignUpForm(UserCreationForm):
    phone_number = forms.CharField(label="Phone Number", widget=forms.NumberInput(attrs={'class': 'input'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'input'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'input'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'phone_number', 'password1', 'password2']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.phone_number = self.cleaned_data.get('phone_number')
        user.save()
        student = Student.objects.create(user=user)
        student.save()
        return user


class UnionSignUpForm(UserCreationForm):
    username = forms.CharField(label="Union Name")
    first_name = forms.CharField(label="Short Name", widget=forms.TextInput(attrs={'class': 'input'}))
    email = forms.EmailField()
    phone_number = forms.CharField(label="Phone Number", widget=forms.NumberInput(attrs={'class': 'input'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'input'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'input'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'email', 'phone_number',  'password1', 'password2']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = False
        user.is_union = True
        user.is_staff = False
        user.phone_number = self.cleaned_data.get('phone_number')
        user.save()
        union = Union.objects.create(user=user)
        return user

accounts/views.py
import random

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import auth
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import CreateView
from twilio.rest import Client

from StudentsCircle.settings import TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER
from .forms import StudentSignUpForm
from .models import User, FriendRequest, Student


# Create your views here.


class StudentRegister(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'accounts/student_register.html'

    def form_valid(self, form):
        user = form.save()
        # student, created = Student.objects.get_or_create(user=user)
        login(self.request, user)
        return redirect('/')


class UserLoginView(LoginView):
    template_name = "accounts/login.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        if self.request.user.is_superuser:
            return '/adminn/'
        return '/'


@login_required(login_url='/accounts/login')
def send_friend_request(request):
    to_id = request.POST['to_id']
    value = request.POST['value']
    sec_user = get_object_or_404(User, id=to_id)

    if value == 'Add Friend':
        f_request, created = FriendRequest.objects.get_or_create(
            from_user=request.user,
            to_user=sec_user)
        return JsonResponse('Cancel', safe=False)
    elif value == 'Cancel':
        f_request = FriendRequest.objects.filter(
            from_user=request.user,
            to_user=sec_user).first()
        f_request.delete()
        return JsonResponse('Add Friend', safe=False)
    elif value == 'Accept':
        f_request = FriendRequest.objects.filter(
            from_user=sec_user,
            to_user=request.user).first()
        user1 = f_request.to_user
        user1.friends.add(sec_user)
        sec_user.friends.add(user1)
        f_request.delete()
        return JsonResponse('Message', safe=False)
    elif value == 'Delete':
        f_request = FriendRequest.objects.filter(
            from_user=sec_user,
            to_user=request.user).first()
        f_request.delete()
        return JsonResponse('Add Friend', safe=False)
    elif value == 'Unfriend':
        request.user.friends.remove(sec_user)
        sec_user.friends.remove(request.user)
        return JsonResponse('Add Friend', safe=False)

    elif value == 'Message':
        return redirect('student:message', sec_user)


def otp_login(request):
    if request.user.is_authenticated:
        return redirect('/')
    elif request.method == 'POST':
        phone_number = request.POST['phone_number']
        if User.objects.filter(phone_number=phone_number).exists():
            user = User.objects.get(phone_number=phone_number)
            request.session['phone_number'] = phone_number

            if user is not None:
                random_num = random.randint(1000, 9999)
                otp = random_num
                request.session['otp'] = otp
                client = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
                message = client.messages.create(
                    body=f"your OTP is {otp}",
                    from_=TWILIO_PHONE_NUMBER,
                    to=f"+919497117447"
                )
                return JsonResponse('true', safe=False)
            else:
                return JsonResponse('upw', safe=False)
        else:
            return JsonResponse('nouser', safe=False)
    else:
        return render(request, 'accounts/otp_login.html')


def enter_otp(request):

    if request.method == 'POST':
        otp1 = request.POST['otp']
        phone_number = request.session['phone_number']
        otp = request.session['otp']
        user = User.objects.get(phone_number=phone_number)

        if int(otp1) == otp:
            auth.login(request, user)
            return JsonResponse('true', safe=False)
    else:
        return render(request, 'accounts/enter_otp.html')


# def post(self,request):
#     try:
#         id = request.user.id
#         # Get database
#         user = User.objects.get(id=id)
#         # Uploaded picture
#         thumb_file = request.FILES['uploadFile']
#         user.picture = thumb_file
#         user.save()
#         to_json_response = {
#                     'state':0
#                     }
#     except Exception as e:
#         print(e)
#         to_json_response={
#                 'state':1
#             }
#     return HttpResponse(json.dumps(to_json_response), content_type='application/json')

templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Students Circle Login</title>
    <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16">

    <link rel="stylesheet" href="{% static 'user/css/main.min.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/weather-icon.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/weather-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/color.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/responsive.css' %}">

</head>
<body>
	<div class="www-layout">
        <section>
        	<div class="gap no-gap signin whitish medium-opacity register">
                <div class="bg-image" style="background-image:url({% static 'user/images/resources/theme-bg.jpg' %})"></div>
                <div class="container">
                	<div class="row">
                        <div class="col-lg-8">
                            <div class="big-ad">
                                <figure><img src="{% static 'user/images/logo2.png' %}" alt=""></figure>
                                <h1>Welcome to the Students Circle</h1>
                                <p>
                                    Students Circle is a social network platform that can be used to connect students of
                                    registered unions. Registered students can perform multipurpose social activities like
                                    study, posting, bloging and much more. Now join & Make Cool Friends around the world !!!
                                </p>
                                <!-- fun fact total users number -->
                                <div class="fun-fact">
<!--                                    <div class="row">-->
<!--                                        <div class="col-lg-3 col-md-3 col-sm-4">-->
<!--                                            <div class="fun-box">-->
<!--                                                <i class="ti-check-box"></i>-->
<!--                                                <h6>Registered People</h6>-->
<!--                                                <span>1,01,242</span>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-lg-3 col-md-3 col-sm-4">-->
<!--                                            <div class="fun-box">-->
<!--                                                <i class="ti-layout-media-overlay-alt-2"></i>-->
<!--                                                <h6>Posts Published</h6>-->
<!--                                                <span>21,03,245</span>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-lg-3 col-md-3 col-sm-4">-->
<!--                                            <div class="fun-box">-->
<!--                                                <i class="ti-user"></i>-->
<!--                                                <h6>Online Users</h6>-->
<!--                                                <span>40,145</span>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
                                </div>
                                <!-- fun fact total users number -->
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="we-login-register">
                                <div class="form-title">
                                    <i class="fa fa-key"></i>Login
                                    <span>Login now and meet the awesome friends around the world.</span>
                                </div>
                                {% if form.errors %}
                                    <p style="color:white">Your username and password didn't match. Please try again.</p>
                                {% endif %}

                                {% if next %}
                                    {% if user.is_authenticated %}
                                    <p>Your account doesn't have access to this page. To proceed,
                                    please login with an account that has access.</p>
                                    {% else %}
                                    <p style="color:white">Please login or create your account to see this page</p>
                                    {% endif %}
                                {% endif %}


                                <form class="we-form" method="post" action="{% url 'accounts:login' %}">
                                    {% csrf_token %}
                                    {{ form.username.error }} {{ form.username.label_tag }} {{ form.username }}
                                    {{ form.password.errors }} {{ form.password.label_tag }} {{ form.password }}
                                    <button type="submit" data-ripple="">Login</button>
                                </form>
                                <span>If your are new to this website? <a class="we-account underline" href="{% url 'accounts:student_register' %}" title=""><h6>SIGNUP</h6></a></span>
                                <a href="{% provider_login_url 'google' %}" class="btn btn-light">Login with Google</a>
                                <span> Login with phone number? <a class="we-account underline" href="{% url 'accounts:otp_login' %}" title=""><h6>OTP login</h6></a></span>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>

    </div>

    	<script src="{% static 'user/js/main.min.js' %}"></script>
		<script src="{% static 'user/js/script.js' %}"></script>
</body>

</html>

templates/accounts/otp_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Students Circle Login</title>
    <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16">

    <link rel="stylesheet" href="{% static 'user/css/main.min.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/weather-icon.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/weather-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/color.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/responsive.css' %}">

</head>
<body>
	<div class="www-layout">
        <section>
        	<div class="gap no-gap signin whitish medium-opacity register">
                <div class="bg-image" style="background-image:url({% static 'user/images/resources/theme-bg.jpg' %})"></div>
                <div class="container">
                	<div class="row">
                        <div class="col-lg-8">
                            <div class="big-ad">
                                <figure><img src="{% static 'user/images/logo2.png' %}" alt=""></figure>
                                <h1>Welcome to the Students Circle</h1>
                                <p>
                                    Students Circle is a social network platform that can be used to connect students of
                                    registered unions. Registered students can perform multipurpose social activities like
                                    study, posting, bloging and much more. Now join & Make Cool Friends around the world !!!
                                </p>
                                <!-- fun fact total users number -->
                                <div class="fun-fact">
<!--                                    <div class="row">-->
<!--                                        <div class="col-lg-3 col-md-3 col-sm-4">-->
<!--                                            <div class="fun-box">-->
<!--                                                <i class="ti-check-box"></i>-->
<!--                                                <h6>Registered People</h6>-->
<!--                                                <span>1,01,242</span>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-lg-3 col-md-3 col-sm-4">-->
<!--                                            <div class="fun-box">-->
<!--                                                <i class="ti-layout-media-overlay-alt-2"></i>-->
<!--                                                <h6>Posts Published</h6>-->
<!--                                                <span>21,03,245</span>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-lg-3 col-md-3 col-sm-4">-->
<!--                                            <div class="fun-box">-->
<!--                                                <i class="ti-user"></i>-->
<!--                                                <h6>Online Users</h6>-->
<!--                                                <span>40,145</span>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
                                </div>
                                <!-- fun fact total users number -->
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="we-login-register">
                                <div class="form-title">
                                    <i class=""></i>Enter Your Phone number
                                    <span>Login now and meet the awesome friends around the world.</span>
                                </div>
                                <form>
                                    <div class="mb-3">
                                        <label class="form-label" for="phone_number">Phone Number</label>
                                        <input type="number" class="form-control" name="phone_number" id="phone_number" placeholder="Enter Your Phone Number">
                                    </div>

                                    <div class="mt-3 text-end">
                                        <span id="errmsg2" style="color:red" class="form-text"></span>
                                        {% for message in messages%}
                                        <h4 style="color:blue"> {{ message }}</h4>
                                        {% endfor %}
                                        <input type="button" id="loginbtn" class="btn btn-info" value="Get OTP">
                                    </div>


                                </form>


                                <span>Login with username and password <a class="we-account underline" href="{% url 'accounts:login' %}" title=""><h6>click here</h6></a></span>
                                <span>If your are new to this website? <a class="we-account underline" href="{% url 'accounts:student_register' %}" title=""><h6>SIGNUP</h6></a></span>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>

    </div>

</body>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script src="{% static 'user/js/my-js.js' %}"></script>



</html>

templates/accounts/student_register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Student Registration</title>
    <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16">

    <link rel="stylesheet" href="{% static 'user/css/main.min.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/weather-icon.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/weather-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/color.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/responsive.css' %}">

</head>
<body>
	<div class="www-layout">
        <section>
        	<div class="gap no-gap signin whitish medium-opacity register">
                <div class="bg-image" style="background-image:url({% static 'user/images/resources/theme-bg.jpg' %})"></div>
                <div class="container">
                	<div class="row">
                        <div class="col-lg-8">
                            <div class="big-ad">
                                <figure><img src="{% static 'user/images/logo2.png' %}" alt=""></figure>
                                <h1>Welcome to the Students Circle</h1>
                                <h3>Get your Free Student Account</h3>
                                <p>
                                    Students Circle is a social network platform that can be used to connect students of
                                    registered unions. Registered students can perform multipurpose social activities
                                    like study, posting, bloging and much more. Now join & Make Cool Friends around the world !!!
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="we-login-register">
                                <div class="form-title">
                                    Student Registration
                                    <span>Sign Up now and meet the awesome friends around the world.</span>
                                </div>
                                <form class="we-form" method="post" >
                                    {% csrf_token %}
                                    {{ form.username.errors }} {{ form.username.label_tag }} {{ form.username }}
                                    {{ form.email.errors }}  {{ form.email.label_tag }} {{ form.email }}
                                    {{ form.phone_number.errors }} {{ form.phone_number.label_tag }} {{ form.phone_number }}
                                    {{ form.password1.errors }} {{ form.password1.label_tag }} {{ form.password1 }}
                                    {{ form.password2.errors }} {{ form.password2.label_tag }} {{ form.password2 }}
                                    <button type="submit" data-ripple="">Register</button>
                                </form>
                                <span>already have an account? <a class="we-account underline" href="{% url 'accounts:login' %}" title=""><h6>LOGIN</h6></a></span>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>

    </div>

    	<script src="{% static 'user/js/main.min.js' %}"></script>
		<script src="{% static 'user/js/script.js' %}"></script>
</body>

</html>