StudentsCircle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminn/', include('adminn.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('student.urls')),
    path('union/', include('union.urls')),
    # path('chat/', include('chat.urls')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# userprofile  = timeline.html/pitpoint-detail.html/pittube-channel.html/
# youtube brain wash for code: - mr robots, cilicon vally

chat/urls.py
from django.urls import path
from .views import index, room
app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

student/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UserHomeView, add_comment, add_like, Timeline, \
    ProfileView, Friends, Unions, edit_fullname, edit_profile_data, \
    select_my_union, upload_pp, chat_room, upload_bg, SingleUserDetailView, SinglePostDetailView, SinglePostUpdateView, \
    SinglePostDeleteView

app_name = 'student'


urlpatterns = [
    path('', UserHomeView.as_view(), name='home'),

    path('add_cmnt/', add_comment, name='add_cmnt'),
    path('add_like/', add_like, name='add_like'),
    path('edit_fullname/', edit_fullname, name='edit_fullname'),
    path('edit_profile_data/', edit_profile_data, name='edit_profile_data'),
    path('select_my_union/', select_my_union, name='select_my_union'),
    path('upload_pp/', upload_pp, name='upload_pp'),
    path('upload_bg/', upload_bg, name='upload_bg'),
    path('chat_room/<int:pk>', chat_room, name='chat_room'),

    path('posts/<int:pk>', UserHomeView.as_view(), name='detail'),
    path('details/<int:pk>', SingleUserDetailView.as_view(), name='details'),
    path('post_details/<int:pk>', SinglePostDetailView.as_view(), name='post_details'),
    path('post_update/<int:pk>', SinglePostUpdateView.as_view(), name='post_update'),
    path('post_delete/<int:pk>', SinglePostDeleteView.as_view(), name='post_delete'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('timeline/', Timeline.as_view(), name='timeline'),
    path('friends/', Friends.as_view(), name='friends'),
    path('unions/', Unions.as_view(), name='unions'),



]

union/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UnionDetailView, MyUnionDetailView, UnionAdminView, union_join_req, upload_union_pp, \
    upload_union_bg, edit_profile_data

app_name = 'union'

urlpatterns = [
    path('details/<int:pk>', UnionDetailView.as_view(), name='details'),
    path('my_union', MyUnionDetailView.as_view(), name='my_union'),
    path('union_admin', UnionAdminView.as_view(), name='union_admin'),
    path('join_req/', union_join_req, name='union_join_req'),
    path('upload_union_pp/', upload_union_pp, name='upload_union_pp'),
    path('upload_union_bg/', upload_union_bg, name='upload_union_bg'),
    path('edit_profile_data/', edit_profile_data, name='edit_profile_data'),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_save


# Create your models here.


class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True, unique=True)
    email = models.EmailField(max_length=150, blank=True, null=True, unique=True)
    is_verified = models.BooleanField(default=False)
    is_union = models.BooleanField(default=False)
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return str(self.username)

    def get_absolute_url(self):
        return reverse('student:details', args=[self.pk])


class Union(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    reg_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    est_date = models.DateField(null=True, blank=True)
    background_img = models.ImageField(upload_to='bg_pic/', height_field=None, width_field=None, null=True)
    logo = models.ImageField(upload_to='union_logo/', height_field=None, width_field=None, null=True)
    college_name = models.CharField(max_length=150, blank=True, null=True)
    college_short_name = models.CharField(max_length=30, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    college_est_date = models.DateField(null=True, blank=True)
    college_logo = models.ImageField(upload_to='collage_logo/', height_field=None, width_field=None, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created

    def __str__(self):
        return str(self.user)


GENDER = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default='Male', null=True, blank=True)
    admission_num = models.BigIntegerField(blank=True, null=True, unique=True)
    batch = models.CharField(max_length=200, blank=True, null=True)
    batch_num = models.BigIntegerField(blank=True, null=True, unique=True)
    union = models.ForeignKey(Union, on_delete=models.CASCADE, blank=True, null=True)
    membership_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    membership_img = models.ImageField(upload_to='memb_pic/', height_field=None, width_field=None, blank=True,
                                       null=True)
    profile_img = models.ImageField(upload_to='profile_pic/', height_field=None, width_field=None, blank=True,
                                    null=True)
    background_img = models.ImageField(upload_to='background_pic/', height_field=None, width_field=None, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created
    # general info
    hobbies = models.TextField(blank=True, null=True)
    interests = ArrayField(models.CharField(max_length=10, default='Arabic', blank=True, null=True), null=True)


def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Student.objects.create(user=instance)
        except:
            pass
# post_save.connect(post_save_user_model_receiver, sender=User)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_user')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


# Explorer, Talker, Admirer, Searcher, Groups and Events


class PointBadges(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userbadge')
    point = models.BigIntegerField(blank=True, null=True)
    badge = ArrayField(models.CharField(max_length=10, default="starter", blank=True, null=True), null=True)


class MemberRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_member')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_member')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


class PageAdmin(models.Model):
    page = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='page')
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

student/models.py
import uuid

from accounts.models import User
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.urls import reverse
from django.utils.text import slugify

# from .signals import delete_post_image , resize_post_image
from .utils import number, incrementor
from django.utils import timezone
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer


# Create your models here.


def upload_post_to(instance, filename):
    return f'post_image/{instance.user.username}/{filename}'


class PostManager(models.Manager):
    def get_posts(self, status: bool = False):
        return (
            self.get_queryset()
                .select_related("user", "user__profile")
                .prefetch_related("likes__profile", "comment_set__user__profile")
                .filter(archived=status)
        )


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=250, unique=False, null=True)
    image = models.FileField(null=True, blank=True, upload_to='post_images/', )
    filetype = models.CharField(max_length=10, blank=True, null=True)
    # likes = models.ManyToManyField(User, related_name="likes", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} : {self.text[:10]}"

    @property
    def image_url(self):
        if self.image == '':
            image = ''
        else:
            image = self.image.url
        return image

    def save(self, *args, **kwargs):
        self.slug = slugify(self.text[:5] + str(number()))
        if not self.image:
            self.image = ""
        if not self.text:
            self.text = ""
        return super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-created"]

    # to find url for each post
    def get_absolute_url(self):
        return reverse('student:detail', args=[self.slug])


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} : {self.user}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()


class SubComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    sub_com = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


# post_delete.connect(delete_post_image, sender=Post)
# post_save.connect(resize_post_image, sender=Post)


class Room(models.Model):
    room_name = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True, editable=False)
    user1 = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user2')


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='m_from_user')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='m_to_user')
    message_type = models.CharField(max_length=10, default='text')
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    message = models.TextField('message')
    # msg_img = models.ImageField(upload_to='msg_img/', height_field=None, width_field=None, blank=True, null=True)
    vid_img = models.FileField(upload_to='vid_img/', blank=True, null=True)
    # aud_img = models.FileField(upload_to='aud_img/', blank=True, null=True)
    # pdf_img = models.FileField(upload_to='pdf_img/', blank=True, null=True)




# class MessageModel(models.Model):
#     """
#     This class represents a chat message. It has a owner (user), timestamp and
#     the message body.
#
#     """
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user',
#                       related_name='m_from_user', db_index=True)
#     recipient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='recipient',
#                            related_name='m_to_user', db_index=True)
#     timestamp = models.DateTimeField('timestamp', auto_now_add=True, editable=False,
#                               db_index=True)
#     body = models.TextField('body')
#
#     def __str__(self):
#         return str(self.id)
#
#     def characters(self):
#         """
#         Toy function to count body characters.
#         :return: body's char number
#         """
#         return len(self.body)
#
#     def notify_ws_clients(self):
#         """
#         Inform client there is a new message.
#         """
#         notification = {
#             'type': 'recieve_group_message',
#             'message': '{}'.format(self.id)
#         }
#
#         channel_layer = get_channel_layer()
#         print("user.id {}".format(self.user.id))
#         print("user.id {}".format(self.recipient.id))
#
#         async_to_sync(channel_layer.group_send)("{}".format(self.user.id), notification)
#         async_to_sync(channel_layer.group_send)("{}".format(self.recipient.id), notification)
#
#     def save(self, *args, **kwargs):
#         """
#         Trims white spaces, saves the message and notifies the recipient via WS
#         if the message is new.
#         """
#         new = self.id
#         self.body = self.body.strip()  # Trimming whitespaces from the body
#         super(MessageModel, self).save(*args, **kwargs)
#         if new is None:
#             self.notify_ws_clients()
#
#     # Meta
#     class Meta:
#         app_label = 'student'

union/models.py
from django.db import models

# Create your models here.

templates/union/union_admin_panel.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% if admin %}
	<section>
		<div class="gap2 gray-bg">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="row merged20" id="page-contents">
							<div class="user-profile">
								<figure style="height:370px; width:1110;">
									{% if union.union.background_img %}
										<img id="cropped_bg" alt="author"  src=" {{ union.union.background_img.url }} "  >
									{% else %}
										<img id="cropped_bg" alt="cropped" src="{% static 'user/images/resources/profile-image.jpg' %}" >
									{% endif %}
									<form action="{% url 'union:upload_union_bg' %}?next={{ request.path }}" method="post"  enctype="multipart/form-data">
										{% csrf_token %}
										<input id="background_img" class="background_img" name="background_img" type="file" hidden>
										<input id="pp_save_btn_bg" type='submit' class="btn btn-success mt-2" value="save" hidden>
									</form>
								</figure>
								<div class="profile-section">
									<div class="row">
										<div class="col-lg-2">
											<div class="profile-author">
												<div class="profile-author-thumb">
													{% if union.logo %}
													<img id="cropped" alt="author"  src=" {{ union.logo.url }} ">
													{% else %}
													<img id="cropped" alt="cropped" src="{% static 'user/images/male.png' %}">
													{% endif %}
													<form action="{% url 'union:upload_union_pp' %}?next={{ request.path }}" method="post">
														{% csrf_token %}
														<textarea name="profile_pic" id="profile_pic" cols="30" rows="10" hidden></textarea>
														<input id="pp_save_btn" type='submit' class="btn btn-success mt-2" value="save" hidden>
													</form>
													<div class="edit-dp">
														<label class="fileContainer">
															<i class="fa fa-camera"></i>
															<input type="file" id="imagecrp" name="imagecrp" accept="image/*"
															   oninput="imagecrp.src=window.URL.createObjectURL(this.files[0])"
															   style="" class="form-control file-upload-info" required>
														</label>
													</div>
												</div>
												<div class="author-content mt-0">
													<a class="author-name" href="#">{{ union.user.first_name|upper }}</a>
													<div class="country">{{ union.user.union.college_short_name }}, {{ union.user.union.location }}</div>
												</div>
											</div>
										</div>
										<div class="col-lg-10">
											<ul class="profile-menu">
												<li>
													<a class="" href="{% url 'union:my_union' %}">Page Details</a>
												</li>
												{% if user.is_staff %}
												<li>
													<a class="" href="{% url 'union:union_admin' %}">Page Admin</a>
												</li>
												{% endif %}
												<li>
							<!--                        <a class="" href="fav-events.html">Events</a>-->
												</li>
							<!--                    <li>-->
							<!--                        <a class="" href="event-calendar.html">Calender</a>-->
							<!--                    </li>-->
											</ul>
											<ol class="folw-detail">
<!--												<li><span>Posts</span><ins>{{ union.post_set.count }}</ins></li>-->
												<li><span>Followers</span><ins>{{ members.count }}</ins></li>
											</ol>
										</div>
									</div>
								</div>
							</div>


							<div class="col-lg-3">
								<aside class="sidebar static right">
									<!-- how it's work video -->
									<!-- page like widget -->

									<div class="widget stick-widget">
										<h4 class="widget-title">Union members</h4>
										<ul class="followers">
											{% for std in members %}
												{% if std.user == request.user %}
													<li>
														<figure>
															{% if std.profile_img %}
																<img src=" {{ std.profile_img.url }} " style="width:45px">
															{% else %}
																<img src="{% static 'user/images/male.png' %}" style="width:45px">
															{% endif %}
														</figure>
														<div class="friend-meta">
															<h4><a href="{% url 'student:details' std.user.pk %}" title=""> {{ std.user.username }}</a></h4>
															<a title="Join Request" class="text-warning  p-0">Admin</a>
														</div>
													</li>
												{% else %}
													<li>
														<figure>
															{% if std.profile_img %}
																<img src=" {{ std.profile_img.url }} " style="width:45px">
															{% else %}
																<img src="{% static 'user/images/male.png' %}" style="width:45px">
															{% endif %}
														</figure>
														<div class="friend-meta">
															<h4><a href="{% url 'student:details' std.user.pk %}" title=""> {{ std.user.username }}</a></h4>
															<a  title="Remove member" class="join_req  p-0" type="submit" data-user_id="{{std.user.id}}" data-union_id="{{std.union.user.id}}">Remove</a>
														</div>
													</li>
												{% endif %}
											{% endfor %}
										</ul>
									</div><!-- other friend list -->
									{% if admin %}
									{% for req in member_requests %}
									<div class="widget">
										<h4 class="widget-title">Member Request</h4>
										<ul class="followers">
											<li>
												<figure><img src="{% static 'user/images/resources/friend-avatar2.jpg' %}" alt=""></figure>
												<div class="friend-meta">
													<h4><a href="time-line.html" title=""> {{ req.from_user }}</a></h4>
													<a  title="Join Request" class="join_req  p-0" type="submit" data-user_id="{{req.from_user.id}}" data-union_id="{{req.to_user.id}}">Accept</a>
													<br>
													<a  title="Join Request" class="join_req  p-0" type="submit" data-user_id="{{req.from_user.id}}" data-union_id="{{req.to_user.id}}">Reject</a>
												</div>
											</li>
										</ul>
									</div><!-- send friend req list -->
									{% endfor %}
									{% endif %}
								</aside>
							</div><!-- sidebar -->
							<div class="col-lg-6">
								{% if admin %}
								<div class="central-meta postbox">
									<span class="create-post">Create post</span>
									<div class="new-postbox">
										<figure>
											{% if union.logo %}
												<img  src=" {{ union.logo.url }} "style="width:30px">
											{% else %}
												<img src="{% static 'user/images/male.png' %}" style="width:30px">
											{% endif %}
										</figure>
										<div class="newpst-input">
											<form method="post" enctype="multipart/form-data">
												{% csrf_token %}
												<textarea name="text" id="" cols="30" rows="10"></textarea>
												<input type="file" name="image" multiple accept="image/*,video/*">
												<button class="post-btn" type="submit" data-ripple="">Post</button>
											</form>
										</div>
									</div>
								</div>
								{% endif %}

                                {% for po in union_post %}
								<div class="central-meta">
									<div class="create-post">Union Updates</div>
									<div class="post-meta">
										{% if po.image_url %}
										<figure>
											{% if po.filetype == 'image' %}
												<img src="{{ po.image_url }}" alt="img" style="">
											{% elif po.filetype == 'video' %}
												<video width="500" height="400" controls>
													<source src="{{ po.image_url }}" type="video/mp4">
													<source src="{{ po.image_url }}" type="video/ogg">
													Your browser does not support the video tag.
												</video>
											{% else %}
												<embed src="{{ po.image_url }}" width="500px" height="400px" />
											{% endif %}
										</figure>
										{% endif %}
										<div class="description">
											<p>{{ po.text }}</p>
											<ul class="like-dislike">
											</ul>
										</div>
										<div class="we-video-info">
											<ul>
												<li>
													{% if post.liked %}
													<div class=" likes heart" style="color:red" title="Like/Dislike" data-post_id="{{post.id}}">❤ <span>{{ post.like_set.count }}</span></div>
													{% else %}
													<div class="like_button likes heart" style="color:#ffb3b3" title="Like/Dislike" data-post_id="{{post.id}}">❤ <span>{{ post.like_set.count }}</span></div>
													{% endif %}
												</li>
												<li>
													<span class="comment" title="Comments">
														<i class="fa fa-commenting"></i>
														<ins>{{ post.comment_set.count }}</ins>
													</span>
												</li>
											</ul>
										</div>

									</div>
								</div>
                                {% endfor %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
<!-------------------------- edit profile modal -------------------------------->
<div class="popup-wraper6">
	<div class="popup login">
		<span class="popup-closed"><i class="ti-close"></i></span>
		<div class="popup-meta">
			<div class="popup-head">
				<h5><i class="ti-key"></i> General Info </h5>
			</div>
				<form class="" method="post">
					{% csrf_token %}
					<div class="col-md-12 login-frm">
						<input type="text" value="{{ me.location }}" name="location" placeholder="Your Place">
						<input type="number" value="{{ me.admission_num }}" name="admission_num" placeholder="Admission Number">
						<input type="number" value="{{ me.batch_num }}" name="batch_num" placeholder="Batch Number">
					</div>
					<button data-ripple="" type="submit" class="main-btn col-md-12">Save</button>
				</form>
		</div>
	</div>
</div>
<!-- croppter =======================================================================-->
<!--MODEL pp-->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
	aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">Crop Image</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body" >
				<div class="box-2">
					<div class="result" style="height:100%"></div>
				</div>
			</div>
			<div class="modal-footer">

				<button type="button" class="btn btn-secondary" data-dismiss="modal">
					Close
				</button>

				<button type="button" id="load" class="btn save btn-primary">
					Save changes
				</button>
			</div>
		</div>
	</div>
</div>
<!-- croppter =======================================================================-->

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
	var like_count = "{{ po.like_set.count }}"
</script>

<script src="{% static 'user/js/my-js.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/0.8.1/cropper.min.js"></script>
<!----------------------------------------->
<!-----------------cropping----------------->
<script>
    $("#cropped_bg").hover(
    function() {
        $('#background_img').removeAttr('hidden')
    },
    function() {
        $('#background_img').attr('hidden', true)
    }
    );
    $("#background_img").change(function() {
        $('#pp_save_btn_bg').removeAttr('hidden')
    });

    $("#background_img").hover(
    function() {
        $('#background_img').removeAttr('hidden')
    },
    function() {
        $('#background_img').attr('hidden', true)
    });

</script>
<script>
var imgSrc;
let result = document.querySelector(".result"),
    save = document.querySelector("#load"),
    cropped = document.querySelector("#cropped"),
    upload = document.querySelector("#imagecrp"),
    cropper = "";

upload.addEventListener("change", (e) => {
    if (e.target.files.length) {
        const reader = new FileReader();

        reader.onload = (e) => {
            if (e.target.result) {
                // create new image
                $("#exampleModalCenter").modal("show");
                let img = document.createElement("img");
                img.id = "image";
                img.src = e.target.result;

                result.innerHTML = "";

                result.appendChild(img);
                cropper = new Cropper(img, {
                    viewMode: 2,
                    aspectRatio: 1/1,
                    autoCropArea: 1,
                    crop: function (e) {
                        console.log(e.detail.x);
                        console.log(e.detail.y);
                    }
                });
            }
        };
        reader.readAsDataURL(e.target.files[0]);
    }
});

save.addEventListener("click", (e) => {
    e.preventDefault();
    console.log('hello----------------');
    imgSrc = cropper
        .getCroppedCanvas({
            width: 300,
            height: 300,
        })
        .toDataURL();
    $("#exampleModalCenter").modal("hide");
    cropped.src = imgSrc;
    $('#profile_pic').val(cropped.src)
    $('#pp_save_btn').removeAttr('hidden');
});
</script>

{% else %}
<center>
	<h1 class="mt-5">Your are not page admin</h1>
	<a class="text-success" href="{% url 'union:my_union' %}"">Go back to previous page</a>
</center>
{% endif %}

{% endblock %}